version: '3.1'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: recovo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: someinsecurepw
    ports:
      - "5432:5432"

  # redis:
  #   image: redis:6.2-alpine
  #   ports:
  #     - 6379:6379

  api:
    stdin_open: true
    tty: true
    build: .
    depends_on:
      - db
      # - redis
    restart: always
    env_file:
      - .env
    volumes:
      - ./app:/code/app
    ports:
      - "8000:8000"

volumes:
  - ./app:/code/app