version: '3.1'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: recovo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: someinsecurepw
    ports:
      - "5432:5432"

  # redis:
  #   image: redis:6.2-alpine
  #   ports:
  #     - 6379:6379

  api:
    stdin_open: true
    tty: true
    build: .
    depends_on:
      - db
      # - redis
    restart: always
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/code
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"

volumes:
   postgres_data:
     driver: local