"""add_color_and_return_address_to_second_hand_product

Revision ID: 3c307f4f5763
Revises: f3bad83f1f27
Create Date: 2025-07-08 12:13:08.922172

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3c307f4f5763"
down_revision: Union[str, None] = "f3bad83f1f27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "second_hand_products", sa.Column("color", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "second_hand_products",
        sa.Column("return_address", sa.String(length=255), nullable=True),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("second_hand_products", "return_address")
    op.drop_column("second_hand_products", "color")

    # ### end Alembic commands ###
