"""add_second_hand_marketplace_tables

Revision ID: add_second_hand_marketplace
Revises: 8552bd7c0abc
Create Date: 2025-06-17 15:08:00.000000

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "add_second_hand_marketplace"
down_revision = "8552bd7c0abc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "second_hand_products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("condition", sa.String(length=20), nullable=False),
        sa.Column("original_sku", sa.String(length=100), nullable=False),
        sa.Column("barcode", sa.String(length=100), nullable=True),
        sa.Column("shopify_product_id", sa.String(length=50), nullable=True),
        sa.Column("seller_id", sa.Integer(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=True),
        sa.Column("is_approved", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_second_hand_products_barcode"),
        "second_hand_products",
        ["barcode"],
        unique=False,
    )
    op.create_index(
        op.f("ix_second_hand_products_id"), "second_hand_products", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_second_hand_products_original_sku"),
        "second_hand_products",
        ["original_sku"],
        unique=False,
    )

    op.create_table(
        "second_hand_product_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["second_hand_products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_second_hand_product_images_id"),
        "second_hand_product_images",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_second_hand_product_images_id"),
        table_name="second_hand_product_images",
    )
    op.drop_table("second_hand_product_images")
    op.drop_index(
        op.f("ix_second_hand_products_original_sku"), table_name="second_hand_products"
    )
    op.drop_index(op.f("ix_second_hand_products_id"), table_name="second_hand_products")
    op.drop_index(
        op.f("ix_second_hand_products_barcode"), table_name="second_hand_products"
    )
    op.drop_table("second_hand_products")
    # ### end Alembic commands ###
