name: Deploy to Stage and Prod

on:
  push:
    branches:
      - main
      - stage  # Changed from staging
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/your-fastapi-app
          tags: |
            type=sha,prefix=,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-stage: # Changed from deploy-staging
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/stage' # Changed from staging
    environment:
      name: stage # Changed from staging
      url: http://${{ secrets.HETZNER_SSH_HOST }}
    steps:
      - name: Deploy to Hetzner Stage
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_SSH_HOST }}
          username: ${{ secrets.HETZNER_SSH_USER }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            export DOCKER_IMAGE_TAG=${{ needs.build-and-push.outputs.image_tag }}
            export DOCKER_IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/your-fastapi-app
            export POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}

            cd /root/my-app

            git pull origin stage # Changed from staging

            docker-compose pull
            docker-compose up -d

  deploy-prod: # Changed from deploy-production
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: prod # Changed from production
      url: http://${{ secrets.HETZNER_SSH_HOST }}
    steps:
      - name: Deploy to Hetzner Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_SSH_HOST }}
          username: ${{ secrets.HETZNER_SSH_USER }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            export DOCKER_IMAGE_TAG=${{ needs.build-and-push.outputs.image_tag }}
            export DOCKER_IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/your-fastapi-app
            export POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}

            cd /root/my-app

            git pull origin main

            docker-compose pull
            docker-compose up -d